export * from './types.js'
export {
  dist, pathLength, bboxOf, bboxUnion, bboxCenter, bboxGap, bboxContains,
  convexHull, polygonArea, polygonPerimeter, minAreaRect,
  largestTriangle, largestQuad, pointInPolygon, turnAngle, pointSegDist,
} from './geometry.js'
export { dedupe, resampleBySpacing, resampleToCount } from './resample.js'
export { rdp } from './simplify.js'
export { detectCorners } from './corners.js'
export { trapezoid } from './fuzzy.js'
export { computeFeatures } from './features.js'
export { classifyStroke } from './classify.js'
export { textShapeFeatures, textProbability } from './entropy.js'
export type { TextShapeFeatures } from './entropy.js'
export { detectSingleStrokeArrow, detectTwoStrokeArrow } from './arrows.js'
export type { ArrowDetection } from './arrows.js'
export { groupStrokes } from './group.js'
export type { GroupOptions } from './group.js'
export { analyzeStrokes } from './scene.js'
export type { AnalyzeOptions } from './scene.js'
export { renderScene, renderStrokes, cropRaster } from './render.js'
export type { RenderOptions, Raster } from './render.js'
export { encodePng } from './png.js'
export { fitCurve, toSvgPath } from './fitcurve.js'
export type { CubicBezier, SvgPathResult } from './fitcurve.js'
export { strokeToEasing } from './easing.js'
export type { Easing } from './easing.js'
